version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    links:
      - php
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      #- "./sites.conf:/etc/nginx/conf.d/sites.conf"
      - "/var/www:/var/www/html"
  php:
    build: .
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "/var/www:/var/www/html"